input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if [logger_name] {
    mutate { add_field => { "service" => "%{logger_name}" } }
  }
  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["127.0.0.1:9200"]
    index => "insurance-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
